name: gohan

on:
  push:
  schedule:
    - cron: '26 21 * * *'
    - cron: '13 2 * * *'
    - cron: '43 7 * * *'
    - cron: '00 22 * * *'
    
  workflow_dispatch:
    


jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          
          pip install line-bot-sdk
          
          pip install tweepy
      - name: Run script
        run:
          python newlinesender.py
