# This is a basic workflow to help you get started with Actions

name: kosenmesi

# Controls when the workflow will run
on:
  schedule:
    - cron: '13 23 * * *'
    - cron: '26 4 * * *'
    - cron: '43 9 * * *'
    - cron: '5 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          
          pip install line-bot-sdk
          
          pip install tweepy
          
      run:
        python newlinesender.py

